=== eChrls/Java/HTML/EsquemasXML/2 Explicacion/notas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="nota" type="tipoNota"/>

    <xs:complexType name="tipoNota">
        <xs:sequence>
            <xs:element name="a" type="xs:string"></xs:element>
            <xs:element name="de" type="xs:string"></xs:element>
            <xs:element name="cabecera" type="tipoCabecera"></xs:element>
            <xs:element name="cuerpo" type="xs:string" minOccurs="0"></xs:element>
            <xs:element name="color" type="xs:string" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

<xs:complexType name="tipoCabecera">
    <xs:sequence>
        <xs:element name="cabeza1"></xs:element>
        <xs:element name="cabeza2"></xs:element>
    </xs:sequence>
    <xs:attribute name="moneda" type="xs:string" fixed="euro" use="required"></xs:attribute>
</xs:complexType>

<xs:complexType name="tipoVacio"></xs:complexType>
</xs:schema>

=== eChrls/Java/HTML/EsquemasXML/2 Explicacion/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<nota xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="notas.xsd">
    <a>Juan</a>
    <de>Susana Marin</de>
    <cabecera moneda="euro">
        <cabeza1>AAAAAAAA</cabeza1>
        <cabeza2></cabeza2>
    </cabecera>
    <cuerpo>CCCC</cuerpo>
    <color>rojo</color>
</nota>
