=== eChrls/Java/HTML/XML/Ejercicios/facturas.dtd
<!ELEMENT factura (datos_cliente, datos_factura)>
<!ATTLIST factura n_fac ID #REQUIRED>

<!ELEMENT datos_cliente (nombreCliente,dirEnvio,poblacion,codPostal, provincia)>
<!ATTLIST datos_cliente id_cli ID #REQUIRED>
<!ELEMENT nombreCliente (#PCDATA)>
<!ELEMENT dirEnvio (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT codPostal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>


<!ELEMENT datos_factura (empresa, pedido)>
<!ATTLIST datos_factura n_ped ID #REQUIRED>

<!ELEMENT empresa (nombre, direccion, cif)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ATTLIST empresa
    telefono CDATA #FIXED "917776688"
    fax CDATA #FIXED "917766999">

<!ELEMENT pedido (fecha, formaPago, productos, baseImponible, ivaPorcentual, ivaEuros, total)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT formaPago (#PCDATA)>
<!ATTLIST formaPago tipo (EFECTIVO|TARJETA|PLAZOS) "EFECTIVO">
<!ELEMENT productos (p+)>
<!ELEMENT baseImponible (#PCDATA)>
<!ATTLIST baseImponible moneda CDATA #FIXED "eur">
<!ELEMENT ivaPorcentual (#PCDATA)>
<!ATTLIST ivaPorcentual porcentaje NMTOKEN #REQUIRED>
<!ELEMENT ivaEuros (#PCDATA)>
<!ATTLIST ivaEuros moneda CDATA #FIXED "eur">
<!ELEMENT total (#PCDATA)>
<!ATTLIST total moneda CDATA #FIXED "eur">

<!ELEMENT p (ref, descripcion, cantidad, precio, iva, importe)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #FIXED "eur">
<!ELEMENT iva (#PCDATA)>
<!ATTLIST iva porcentaje NMTOKEN #REQUIRED>
<!ELEMENT importe (#PCDATA)>
<!ATTLIST importe moneda CDATA #FIXED "eur">

=== eChrls/Java/HTML/XML/Ejercicios/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "facturas.dtd">
<factura n_fac="_999">
    <datos_cliente id_cli="_879">
        <nombreCliente>Dario Bueno</nombreCliente>
        <dirEnvio>Av. Oporto nยบ7</dirEnvio>
        <poblacion>Madrid</poblacion>
        <codPostal>28043</codPostal>
        <provincia>Madrid</provincia>
    </datos_cliente>
    <datos_factura n_ped="_731">
        <empresa telefono="917776688" fax="917766999">
            <nombre>Equipos Digitales S.L.</nombre>
            <direccion>Av.Valladolid Madrid 28015</direccion>
            <cif>Q-9876543</cif>
        </empresa>
        <pedido>
            <fecha>12-01-2005</fecha>
            <formaPago tipo="EFECTIVO">EFECTIVO</formaPago>
            <productos>
                <p>
                    <ref>150564056456</ref>
                    <descripcion>MICRO PENTIUM IV</descripcion>
                    <cantidad>1</cantidad>
                    <precio moneda="eur">230</precio>
                    <iva porcentaje="16.0">16.00</iva>
                    <importe moneda="eur">266.80</importe>
                </p>
                <p>
                    <ref>150564056456</ref>
                    <descripcion>MICRO PENTIUM IV</descripcion>
                    <cantidad>1</cantidad>
                    <precio moneda="eur">230</precio>
                    <iva porcentaje="16.0">16.0</iva>
                    <importe moneda="eur">266.80</importe>
                </p>
                <p>
                    <ref>150564056456</ref>
                    <descripcion>MICRO PENTIUM IV</descripcion>
                    <cantidad>1</cantidad>
                    <precio>230</precio>
                    <iva porcentaje="16.0">16.0</iva>
                    <importe moneda="eur">266.80</importe>
                </p>
            </productos>
            <baseImponible moneda="eur">970.00</baseImponible>
            <ivaPorcentual porcentaje="16.0">16.0</ivaPorcentual>
            <ivaEuros moneda="eur">155.20</ivaEuros>
            <total moneda="eur">1125.20</total>
        </pedido>
    </datos_factura>
</factura>
