<!-- DTD - Ejercicio 1 - Elementos sin atributos -->

<!-- 1. Números (dtd1_1.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE numeros [
    <!ELEMENT numeros (numero)>
    <!ELEMENT numero (#PCDATA)>
]>
<numeros>
    <numero>25</numero>
</numeros>

<!-- 2. Letras (dtd1_2.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE letras [
    <!ELEMENT letras (letra+)>
    <!ELEMENT letra (#PCDATA)>
]>
<letras>
    <letra>m</letra>
    <letra>uve doble</letra>
</letras>

<!-- 3. Colores (dtd1_3.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
    <!ELEMENT colores (color*)>
    <!ELEMENT color (#PCDATA)>
]>
<colores>
    <color>azul marino</color>
    <color>amarillo</color>
</colores>

<!-- 4. Flores (dtd1_4.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flores [
    <!ELEMENT flores (flor+)>
    <!ELEMENT flor (#PCDATA)>
]>
<flores>
    <flor>Rosa</flor>
</flores>

<!-- 5. Animales (dtd1_5.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animales [
    <!ELEMENT animales (animal*)>
    <!ELEMENT animal (#PCDATA)>
]>
<animales>
    <animal>Caniche</animal>
    <animal>Siamés</animal>
</animales>

<!-- 6. Escritores (dtd1_6.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escritores [
    <!ELEMENT escritores (escritor*)>
    <!ELEMENT escritor (nombre, nacimiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT nacimiento (#PCDATA)>
]>
<escritores>
    <escritor>
        <nombre>Mario Vargas LLosa</nombre>
        <nacimiento>28 de marzo de 1936</nacimiento>
    </escritor>
    <escritor>
        <nombre>Milan Kundera</nombre>
        <nacimiento>1 de abril de 1929</nacimiento>
    </escritor>
</escritores>

<!-- 7. Músicos (dtd1_7.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicos [
    <!ELEMENT musicos (musico*)>
    <!ELEMENT musico ((nombre | apodo), fechaNacimiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apodo (#PCDATA)>
    <!ELEMENT fechaNacimiento (#PCDATA)>
]>
<musicos>
    <musico>
        <nombre>Antonio Vivaldi</nombre>
        <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
    </musico>
    <musico>
        <nombre>Johann Sebastian Bach</nombre>
        <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
    </musico>
</musicos>

<!-- 8. Teléfonos de emergencia (dtd1_8.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto*)>
    <!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT telefonoFijo (#PCDATA)>
    <!ELEMENT telefonoMovil (#PCDATA)>
]>
<agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>112 (Unión Europea)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
        <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
    </contacto>
</agenda>

<!-- 9. El sistema solar (dtd1_9.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistemaSolar [
    <!ELEMENT sistemaSolar (cuerpo*)>
    <!ELEMENT cuerpo (planeta|satelite|asteroide)>
    <!ELEMENT planeta (#PCDATA)>
    <!ELEMENT satelite (#PCDATA)>
    <!ELEMENT asteroide (#PCDATA)>
]>
<sistemaSolar>
    <cuerpo>
        <planeta>Tierra</planeta>
    </cuerpo>
    <cuerpo>
        <satelite>Luna</satelite>
    </cuerpo>
    <cuerpo>
        <asteroide>Ceres</asteroide>
    </cuerpo>
</sistemaSolar>

<!-- DTD - Ejercicio 2 - Elementos sin atributos -->

<!-- 1. Marcadores (dtd2_1.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores [
    <!ELEMENT marcadores (marcador+)>
    <!ELEMENT marcador (nombre, uri)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT uri (#PCDATA)>
]>
<marcadores>
    <marcador>
        <nombre>W3C</nombre>
        <uri>http://www.w3.org/</uri>
    </marcador>
    <marcador>
        <nombre>Web Hypertext Application Technology Working Group (WHATWG)</nombre>
        <uri>http://www.whatwg.org/</uri>
    </marcador>
</marcadores>

<!-- 2. Efemérides (dtd2_2.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE efemerides [
    <!ELEMENT efemerides (efemeride+)>
    <!ELEMENT efemeride (fecha, hecho)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT hecho (#PCDATA)>
]>
<efemerides>
    <efemeride>
        <fecha>20 de julio de 1969</fecha>
        <hecho>Llegada del hombre a la Luna</hecho>
    </efemeride>
    <efemeride>
        <fecha>12 de octubre de 1492</fecha>
        <hecho>Llegada de Colón a América</hecho>
    </efemeride>
    <efemeride>
        <fecha>6 de abril de 1909</fecha>
        <hecho>llegada de Robert Peary al Polo Norte</hecho>
    </efemeride>
</efemerides>

<!-- 3. Aeropuertos (dtd2_3.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuertos [
    <!ELEMENT aeropuertos (aeropuerto*)>
    <!ELEMENT aeropuerto (nombre, cerrado?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT cerrado EMPTY>
]>
<aeropuertos>
    <aeropuerto>
        <nombre>Berlín Schönefeld (SFX)</nombre>
    </aeropuerto>
    <aeropuerto>
        <nombre>Berlín Tempelhof (THF)</nombre>
        <cerrado />
    </aeropuerto>
</aeropuertos>

<!-- 4. Vuelos (dtd2_4.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vuelos [
    <!ELEMENT vuelos (vuelo*)>
    <!ELEMENT vuelo (origen, destino)>
    <!ELEMENT origen (#PCDATA)>
    <!ELEMENT destino (#PCDATA)>
]>
<vuelos>
    <vuelo>
        <origen>Valencia (VLC)</origen>
        <destino>Londres Heathrow (LHR)</destino>
    </vuelo>
    <vuelo>
        <origen>Paris Charles de Gaulle (CDG)</origen>
        <destino>Berlín Schönefeld (SFX)</destino>
    </vuelo>
</vuelos>

<!-- 5. Reyes españoles (dtd2_5.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reyesEspa ñoles [
    <!ELEMENT reyesEspañoles ((rey | reina)*)>
    <!ELEMENT rey (nombre, padre, madre)>
    <!ELEMENT reina (nombre, padre, madre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT padre (#PCDATA)>
    <!ELEMENT madre (#PCDATA)>
]>
<reyesEspañoles>
    <rey>
        <nombre>Felipe III</nombre>
        <padre>Felipe II</padre>
        <madre>Ana de Austria</madre>
    </rey>
    <reina>
        <nombre>Juana la Loca</nombre>
        <padre>Fernando el Católico</padre>
        <madre>Isabel la Católica</madre>
    </reina>
    <rey>
        <nombre>Carlos I</nombre>
        <padre>Felipe el Hermoso</padre>
        <madre>Juana la Loca</madre>
    </rey>
</reyesEspañoles>

<!-- 6. Países (dtd2_6.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
    <!ELEMENT paises (pais*)>
    <!ELEMENT pais (nombre, unionEuropea?, otan?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT unionEuropea EMPTY>
    <!ELEMENT otan EMPTY>
]>
<paises>
    <pais>
        <nombre>España</nombre>
        <unionEuropea />
        <otan />
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan />
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea />
    </pais>
</paises>

<!-- 7. Códigos de colores (dtd2_7.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
    <!ELEMENT colores (color*)>
    <!ELEMENT color (nombreSvg, codigo)>
    <!ELEMENT nombreSvg (#PCDATA)>
    <!ELEMENT codigo (rgb | cmyk)>
    <!ELEMENT rgb (#PCDATA)>
    <!ELEMENT cmyk (#PCDATA)>
]>
<colores>
    <color>
        <nombreSvg>Purple</nombreSvg>
        <codigo>
            <rgb>#800080</rgb>
        </codigo>
    </color>
    <color>
        <nombreSvg>Purple</nombreSvg>
        <codigo>
            <cmyk>#00FF007F</cmyk>
        </codigo>
    </color>
</colores>

<!-- 8. Contabilidad (dtd2_8.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
    <!ELEMENT contabilidad (apunte*)>
    <!ELEMENT apunte ((ingreso | gasto), fecha, cantidad, concepto)>
    <!ELEMENT ingreso EMPTY>
    <!ELEMENT gasto EMPTY>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT concepto (#PCDATA)>
]>
<contabilidad>
    <apunte>
        <ingreso />
        <fecha>24 de febrero de 2011</fecha>
        <cantidad>1800,00 €</cantidad>
        <concepto>Salario</concepto>
    </apunte>
    <apunte>
        <gasto />
        <fecha>28 de febrero de 2011</fecha>
        <cantidad>74,25 €</cantidad>
        <concepto>Recibo luz</concepto>
    </apunte>
</contabilidad>

<!-- 9. Mensajes (dtd2_9.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensajes [
    <!ELEMENT mensajes (mensaje+)>
    <!ELEMENT mensaje (de, para, hora, texto)>
    <!ELEMENT de (#PCDATA)>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT hora (#PCDATA)>
    <!ELEMENT texto (#PCDATA | strong)*>
    <!ELEMENT strong (#PCDATA)>
]>
<mensajes>
    <mensaje>
        <de>Pepe (pepe@example.com)</de>
        <para>Juan (juan@example.com)</para>
        <hora>28/02/2011 17:48:23,61</hora>
        <texto>¿Hola, Juan, qué haces?</texto>
    </mensaje>
    <mensaje>
        <de>Juan (juan@example.com)</de>
        <para>Pepe (pepe@example.com)</para>
        <hora>28/02/2011 17:54:20,87</hora>
        <texto>Aquí, aprendiendo <strong>XML</strong></texto>
    </mensaje>
</mensajes>

<!-- DTD - Ejercicio 3 - Elementos con atributos -->

<!-- 1. Datos personales (dtd3_1.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona [
    <!ELEMENT persona EMPTY>
    <!ATTLIST persona
        nombre CDATA #IMPLIED
        dni CDATA #IMPLIED>
]>
<persona nombre="John Doe" dni="03141592E" />

<!-- 2. Película (dtd3_2.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicula [
    <!ELEMENT pelicula EMPTY>
    <!ATTLIST pelicula
        titulo CDATA #IMPLIED
        genero CDATA #IMPLIED>
]>
<pelicula titulo="La diligencia" genero="oeste" />

<!-- 3. Cuadros (dtd3_3.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cuadros [
    <!ELEMENT cuadros (cuadro*)>
    <!ELEMENT cuadro EMPTY>
    <!ATTLIST cuadro
        titulo ID #REQUIRED
        autor CDATA #REQUIRED>
]>
<cuadros>
    <cuadro titulo="AdanYEva_Durero" autor="Alberto Durero" />
    <cuadro autor="Lucas Cranach, el viejo" titulo="AdanYEva_Cranach" />
</cuadros>

<!-- 4. Lista de la compra (dtd3_4.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaCompra [
    <!ELEMENT listaCompra (item*)>
    <!ELEMENT item EMPTY>
    <!ATTLIST item
        nombre CDATA #REQUIRED
        cantidad CDATA #REQUIRED>
]>
<listaCompra>
    <item nombre="leche" cantidad="12 litros" />
    <item nombre="pan" cantidad="3 barras de cuarto" />
</listaCompra>

<!-- 5. Jugadores de fútbol (dtd3_5.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol [
    <!ELEMENT futbol (jugador*)>
    <!ELEMENT jugador EMPTY>
    <!ATTLIST jugador
        nombre CDATA #REQUIRED
        codigo ID #REQUIRED>
]>
<futbol>
    <jugador nombre="Alfredo Di Stéfano" codigo="1" />
    <jugador nombre="Edson Arantes do Nascimento, Pelé" codigo="2" />
    <jugador nombre="Diego Armando Maradona" codigo="3" />
    <jugador nombre="Johan Cruyff" codigo="4" />
</futbol>

<!-- 6. Jugadores y equipos de fútbol (dtd3_6.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol [
    <!ELEMENT futbol ((jugador|equipo)*)>
    <!ELEMENT jugador EMPTY>
    <!ATTLIST jugador
        nombre CDATA #REQUIRED
        codigo ID #REQUIRED>
    <!ELEMENT equipo EMPTY>
    <!ATTLIST equipo
        nombre CDATA #REQUIRED
        jugadores IDREFS #IMPLIED>
]>
<futbol>
    <jugador nombre="Alfredo Di Stéfano" codigo="ads" />
    <jugador nombre="Edison Arantes do Nascimento" codigo="ean" />
    <jugador nombre="Diego Armando Maradona" codigo="dam" />
    <jugador nombre="Johan Cruyff" codigo="jc" />
    <equipo nombre="Società Sportiva Calcio Napoli" jugadores="dam" />
    <equipo nombre="Futbol Club Barcelona" jugadores="jc dam" />
</futbol>

<!-- DTD - Ejercicio 4 - Elementos con atributos - Corregir errores en la DTD -->

<!-- 1. Libro (dtd4_1.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro [
    <!ELEMENT libro EMPTY>
    <!ATTLIST libro autor CDATA #REQUIRED>
]>
<libro autor="Mario Vargas LLosa" />

<!-- 2. Inventores (dtd4_2.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventores [
    <!ELEMENT inventores (inventor*)>
    <!ELEMENT inventor EMPTY>
    <!ATTLIST inventor
        invento CDATA #REQUIRED
        nombre ID #REQUIRED>
]>
<inventores>
    <inventor nombre="Robert_Adler" invento="Mando a distancia" />
    <inventor nombre="Laszlo_Josef_Biro" invento="Bolígrafo" />
    <inventor nombre="Josephine_Garis_Cochran" invento="Lavaplatos" />
    <inventor nombre="Anonimo" invento="Fuego" />
</inventores>

<!-- 3. Cosas por hacer (dtd4_3.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cosasPorHacer [
    <!ELEMENT cosasPorHacer (cosa*)>
    <!ELEMENT cosa (#PCDATA)>
    <!ATTLIST cosa
        fecha CDATA #REQUIRED
        fechaLimite CDATA #REQUIRED>
]>
<cosasPorHacer>
    <cosa fecha="20 de febrero de 2011" fechaLimite="1 de marzo de 2011">
        Preparar ejercicios de DTDs</cosa>
    <cosa fecha="21 de febrero de 2011" fechaLimite="5 de marzo de 2011">
        Preparar tema XSLT</cosa>
</cosasPorHacer>

<!-- 4. Resoluciones de pantalla (dtd4_4.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resoluciones [
    <!ELEMENT resoluciones (resolucion*)>
    <!ELEMENT resolucion EMPTY>
    <!ATTLIST resolucion
        nombre NMTOKEN #REQUIRED
        alto CDATA #REQUIRED
        ancho CDATA #REQUIRED>
]>
<resoluciones>
    <resolucion nombre="VGA" alto="480" ancho="640" />
    <resolucion nombre="XGA" alto="1024" ancho="768" />
    <resolucion nombre="HD_1080" alto="1920" ancho="1080" />
</resoluciones>

<!-- 5. Álbumes de Mortadelo y Filemón (dtd4_5.xml) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albumesMortadelo [
    <!ELEMENT albumesMortadelo (album*)>
    <!ELEMENT album EMPTY>
    <!ATTLIST album
        nombre CDATA #REQUIRED
        fecha (1969|1970|1971|1972|1973|1974) #REQUIRED>
]>
<albumesMortadelo>
    <album nombre="El sulfato atómico" fecha="1969" />
    <album nombre="La caja de diez cerrojos" fecha="1971" />
    <album nombre="El otro yo del profesor Bacterio" fecha="1973" />
    <album nombre="Los cacharros majaretas" fecha="1974" />
</albumesMortadelo>

<!-- DTD - Ejercicio 5 - DTDs alternativos -->

a) DTD sin atributos:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga [
    <!ELEMENT liga (partido+)>
    <!ELEMENT partido (local, visitante, golesLocal, golesVisitante)>
    <!ELEMENT local (#PCDATA)>
    <!ELEMENT visitante (#PCDATA)>
    <!ELEMENT golesLocal (#PCDATA)>
    <!ELEMENT golesVisitante (#PCDATA)>
]>
<liga>
    <partido>
        <local>Nottingham Presa</local>
        <visitante>Inter de Mitente</visitante>
        <golesLocal>0</golesLocal>
        <golesVisitante>1</golesVisitante>
    </partido>
    <partido>
        <local>Vodka Juniors</local>
        <visitante>Sparta da Risa</visitante>
        <golesLocal>3</golesLocal>
        <golesVisitante>3</golesVisitante>
    </partido>
    <partido>
        <local>Water de Munich</local>
        <visitante>Esteaua es del grifo</visitante>
        <golesLocal>4</golesLocal>
        <golesVisitante>2</golesVisitante>
    </partido>
</liga>

b) DTD con goles como atributos:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga [
    <!ELEMENT liga (partido+)>
    <!ELEMENT partido (local, visitante)>
    <!ELEMENT local (#PCDATA)>
    <!ELEMENT visitante (#PCDATA)>
    <!ATTLIST partido
        golesLocal CDATA #REQUIRED
        golesVisitante CDATA #REQUIRED>
]>
<liga>
    <partido golesLocal="0" golesVisitante="1">
        <local>Nottingham Presa</local>
        <visitante>Inter de Mitente</visitante>
    </partido>
    <partido golesLocal="3" golesVisitante="3">
        <local>Vodka Juniors</local>
        <visitante>Sparta da Risa</visitante>
    </partido>
    <partido golesLocal="4" golesVisitante="2">
        <local>Water de Munich</local>
        <visitante>Esteaua es del grifo</visitante>
    </partido>
</liga>

c) DTD con toda la información como atributos:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga [
    <!ELEMENT liga (partido+)>
    <!ELEMENT partido EMPTY>
    <!ATTLIST partido
        local CDATA #REQUIRED
        visitante CDATA #REQUIRED
        golesLocal CDATA #REQUIRED
        golesVisitante CDATA #REQUIRED>
]>
<liga>
    <partido local="Nottingham Presa" visitante="Inter de Mitente" golesLocal="0" golesVisitante="1" />
    <partido local="Vodka Juniors" visitante="Sparta da Risa" golesLocal="3" golesVisitante="3" />
    <partido local="Water de Munich" visitante="Esteaua es del grifo" golesLocal="4"
        golesVisitante="2" />
</liga>