<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Relacion de ejercicios DTD FINAL-->
<!-- José Carlos Torralvo 1º DAW-->

<!-- Ejercicio 1-->
<!DOCTYPE etiqueta[
<!ELEMENT etiqueta (nombre, calle, pais, codigo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
]>
<etiqueta>
<nombre>Pepe García</nombre>
<calle>C/Ronda, 3</calle>
<pais>España</pais>
<codigo>18465</codigo>
</etiqueta>


<!-- Ejercicio 2
Tras corregir los errores del ejercicio 1.- elabora su DTD-->
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE etiqueta SYSTEM "etiqueta.dtd">
<etiqueta id="1">
<nombre>Pepe García</nombre>
<calle>C/Ronda, 3</calle>
<pais>España</pais>
<codigo>18465</codigo>
</etiqueta>


<!-- etiqueta.dtd -->
<!ELEMENT etiqueta (nombre, calle, pais, codigo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>



<!-- Ejercicio 3
Determina y corrige el/los error/errores que provoca que el fichero XML no sea válido
respecto al ejemplo-agenda.dtd: -->

<!-- Fichero: ejemplo-agenda.dtd -->
<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, tlf)>
<!ATTLIST persona id #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>


<!-- Fichero: prueba.xml -->
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE agenda SYSTEM "ejemplo-agenda.dtd">
<agenda>
<persona>
<nombre>Ricardo Borriquero</nombre>
<tlf>951345678</tlf>
</persona>
<persona>
<nombre>Eva Risto</nombre>
<tlf>955837659</tlf>
</persona>
</agenda>