=== eChrls/Java/HTML/EXAMEN_DTD_JCARLOSTORRALVO/Correccion/biblioteca.dtd
<!ELEMENT biblioteca (libros, autores, editoriales)>
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, precio, fechaPub, revisiones?)>
<!ATTLIST libro
    isbn ID #REQUIRED
    editorial IDREF #REQUIRED
    autores IDREFS #REQUIRED
    >
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda (euro) #REQUIRED><!-- Obligacion a que lleve atributo moneda-->
<!ELEMENT fechaPub (#PCDATA)>
<!ELEMENT revisiones (revision+)>
<!ELEMENT revision (valoracion, comentario)>
<!ATTLIST revision autor IDREF #REQUIRED>
<!ELEMENT valoracion (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>

<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre, apellido, email?)>
<!ATTLIST autor nif ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT editoriales (editorial+)>
<!ELEMENT editorial (oficina, web)>
<!ATTLIST editorial nombre ID #REQUIRED>
<!ELEMENT oficina (#PCDATA)>
<!ELEMENT web (#PCDATA)>

=== eChrls/Java/HTML/EXAMEN_DTD_JCARLOSTORRALVO/Correccion/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libros>
        <libro isbn="_55555_777" editorial="McGraw-Hill" autores="_23456788P _23456777G">
            <titulo>Fundamentos de bbdd</titulo>
            <precio moneda="euro">40</precio> <!-- Obligacion a que lleve atributo moneda-->
            <fechaPub>2003</fechaPub>
            <revisiones>
                <revision autor="_23456789N">
                    <valoracion>8.5</valoracion>
                    <comentario>Libro de texto base</comentario>
                </revision>
            </revisiones>
        </libro>
    </libros>
    <autores>
        <autor nif="_23456788P">
            <nombre>Abraham</nombre>
            <apellido>Silver</apellido>
            <email>silver@gmail.com</email>
        </autor>
        <autor nif="_23456777G">
            <nombre>Henry</nombre>
            <apellido>Korth</apellido>
            <email>korth@gmail.com</email>
        </autor>
        <autor nif="_23456789N">
            <nombre>James</nombre>
            <apellido>Smith</apellido> <!-- El email no era obligatorio-->
        </autor>
    </autores>
    <editoriales>
        <editorial nombre="McGraw-Hill">
            <oficina>Av.Santander s/n</oficina>
            <web>www.mcgrawhill.com</web>
        </editorial>
    </editoriales>
</biblioteca>
